name: 'Text field storage'
description: 'Text field storage configuration and Basic HTML text format and editor.'
type: 'Field storage'
install:
  - ckeditor5
  - node
  - text
# Contrib
  - linkit
config:
  import:
    linkit:
      - 'image.style.linkit_result_thumbnail'
      - 'linkit.linkit_profile.default'
# All roles can use Basic html where allowed (not on ride pages).
  actions:
    user.role.authenticated:
      grantPermission: 'use text format basic_html'
